using System;

namespace CSharpFundamentals
{
    public class Person
    {
        // autogenerated props at the top
        public string Name { get; set; }
        public string Username { get; set; }
        public DateTime Birthdate { get; private set; }

        public Person(DateTime birthdate)
        {
            Birthdate = birthdate;
        }

        public int Age
        {
            get
            {
                var timespan = DateTime.Now - Birthdate;
                var years = timespan.Days / 365;

                return years;
            }


        }
    }
}
